"""Added Prices table

Revision ID: 4af1fa0d8413
Revises:
Create Date: 2026-01-29 17:23:26.181975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4af1fa0d8413"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("captured_ts_ms", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticker", "captured_ts_ms", name="uq_prices_ticker_captured_ts_ms"
        ),
    )
    op.create_index(
        "ix_prices_captured_ts_ms", "prices", ["captured_ts_ms"], unique=False
    )
    op.create_index(
        "ix_prices_ticker_captured_ts_ms",
        "prices",
        ["ticker", "captured_ts_ms"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prices_ticker_captured_ts_ms", table_name="prices")
    op.drop_index("ix_prices_captured_ts_ms", table_name="prices")
    op.drop_table("prices")
    # ### end Alembic commands ###
